# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc5cdb5370171a5a25ebbd24ad06189ec6c0588bee323affc89fa924dd9f99290d9de242ba619ecb207558ae6eeb804e39bf8149bbfcd4948af7ec42129a1a3a

test:
  secret_key_base: e162a3759db3ebcee8823ae53a34f5d963666aaf3c9e452e68fca916d69eb1a78aa26f4669f47c5928d1bb52ac6aa4aeb5f26ddd3549dc3a1e74379bde14efb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
